.gitmodules, Cargo.toml, src/lib.rs, src/package_set.rs, src/syntax_definition.rs
Walks a directory and loads all the syntaxes in it.
=> Package loading

src/dumps.rs, src/easy.rs, src/highlighting/highlighter.rs, src/highlighting/theme_set.rs, src/html.rs, src/parsing/parser.rs, src/parsing/scope.rs, src/parsing/syntax_set.rs, src/parsing/yaml_load.rs, src/util.rs
It still has some things it doesn't like (e.g. acronyms in doc comments) and wants me to use map_or and friends. I don't care about that stuff, though.
=> Make Clippy Happy

src/highlighting/theme_set.rs
Also refactors the internals of get_theme to use the newly created API.
=> Adds the ability to load theme from streams

src/parsing/parser.rs, src/parsing/syntax_definition.rs
This PR will only compile after https://github.com/rust-onig/rust-onig/pull/17 has been merged.
=> Derive Eq and PartialEq for the two state structs [ DO NOT MERGE ]

src/highlighting/highlighter.rs, src/highlighting/theme.rs, src/highlighting/theme_set.rs, src/parsing/parser.rs, src/parsing/scope.rs, src/parsing/syntax_definition.rs, src/parsing/syntax_set.rs, src/parsing/yaml_load.rs
Just a few readability improvements.
=> fixed some clippy warnings

Readme.md
Closes https://github.com/trishume/syntect/issues/23.
=> Note how to update submodules

src/highlighting/highlighter.rs
I... think this is right? 🤷‍♂️
=> Added Highlighter::style_for_stack

src/highlighting/style.rs
This is slightly speculative, but I _expect_ we'll go this route in xi and this seems like a reasonable API to expose in general.
=> Add StyleModifier::apply

src/highlighting/highlighter.rs
I'm reasonably confident this is the only modification I'll have to make in the near future. If you have time to do a release, I'll PR the last bit of the style/theme changes into xi-core. 🙏
=> Expose merging of StyleModifiers via Hightlighter

Cargo.toml, Readme.md, examples/parsyncat.rs
See #20.
@trishume It might be good to add the recommendation to #20 and #29, before closing them. I imagine it would carry more weight coming from the project owner, too :)
=> Recommend rayon, add examples/documentation of parallel usage

src/parsing/parser.rs
I'm working on #76. This is a small change so that we can add some more tests for checking the "nonewlines" mode.
=> Change parsing tests to also run against "nonewlines" syntax definition

src/parsing/parser.rs
Also parse the Ruby heredoc as individual lines.
=> Split up can_parse test

Readme.md
Closes https://github.com/trishume/syntect/issues/95
=> Readme: Add "Projects using Syntect" section + mention syntect_server

.travis.yml, codecov.yml
Also enable caching and building on beta/nightly.
=> Travis: Add coverage using cargo-tarpaulin and codecov

src/parsing/parser.rs, src/parsing/syntax_set.rs, src/parsing/yaml_load.rs
supersedes https://github.com/trishume/syntect/pull/61
=> pass fallback name based on syntax filename to the YAML loader

Cargo.toml, src/dumps.rs
Changelog: https://github.com/TyOverby/bincode/blob/master/changelist.org#100
=> Upgrade bincode to 1.0

.travis.yml
See xd009642/tarpaulin#77
(Error can be seen here: https://travis-ci.org/trishume/syntect/jobs/370437688 and codecov is sad: https://codecov.io/gh/trishume/syntect)
=> travis: Require sudo to fix cargo-tarpaulin

examples/syncat.rs
I implemented this for diagnosing #97
=> Add ability to run syncat with nonewlines

examples/syntest.rs
The test file name is printed again so that it's easy to grep only for
the timing, and then graph it.
(I used this for #150.)
=> Add --time option to syntest

src/parsing/syntax_set.rs
Some files like `CMakeLists.txt` have a file extension that does not
specify the correct syntax.
This commit changes the order of the syntax lookup such that we
search for the whole filename first and fall back to the file
extension if there were no matches.
closes #169
=> Search for filename before file extension

Cargo.toml
=> Upgrade to regex 1.0

Cargo.toml
Fixed version of #191, thanks @kornelski and @iwillspeak!
=> Bump onig to v4.1

src/util.rs
=> Add `LinesWithEndings` util for iterating over lines (#196)

.travis.yml, CHANGELOG.md, Cargo.toml, Readme.md, examples/syncat.rs, src/lib.rs
Includes final fixes to docs and readme for v3.0 release, also I wrote a changelog with details of the breaking changes and tips on upgrading.
I also revamped the Readme to make it more helpful.
Finally, sorry this took so long 🎉
=> Release v3.0

Readme.md
Very thanks for your awesome project, I have write a program named [hors](https://github.com/WindSoilder/hors)
Which is using `syntect` to support code highlighting feature.  And it works fine to me :)
=> add hors into projects using syntect.

Readme.md
The project was recently renamed to Zola
=> Change Gutenberg to Zola in readme

src/highlighting/highlighter.rs
There're situations where it is useful to know the range of a
highlighted substring in the source string. For example, to just
paint existing text instead of rebuilding it (i.e in a text editor).
This implements a `RangedHighlightIterator` in a backwards
compatible manner, so that the previous `HighlightIterator`
still exists but uses the same implementation.
=> Added `RangedHighlightIterator`

Cargo.toml
=> Upgrade to criterion 0.3 and plist 0.5

Readme.md
=> Add The Way to "Projects using Syntect"

Cargo.toml, src/html.rs
=> remove dependency on assets for html feature - just use it for tests

Cargo.toml
=> Bump fancy-regex to 0.7

src/easy.rs
Simple change to also expose the `Range` of the scope and not just the string slice in `ScopeRegionIterator`. 
This is super useful for building custom parsing logic on top of syntect without using the highlighter (which also has `HighlightIterator` and `RangedHighlightIterator`).
=> Add ScopedRangeIterator

src/util.rs
Hello,
thank you for this great library. I'm building [hgrep](https://github.com/rhysd/hgrep) on it and it works greatly.
Colors have alpha values for their transparency. But they are ignored in `utils::as_24_bit_terminal_escaped`.
This PR blends foreground colors and background colors when the foreground color's alpha value is not max (=255) so that the alpha value is now reflected to the converted ANSI color sequence.
I was inspired by [the implementation in Neovim](https://github.com/neovim/neovim/blob/649b3160a10f0053747383f0703b0a5a94548570/src/nvim/highlight.c#L526-L626), which is a famous text editor.
=> Blend alpha value on converting colors to ANSI color sequences

src/parsing/syntax_set.rs
This is one step towards fixing https://github.com/trishume/syntect/issues/421 / https://github.com/sharkdp/bat/issues/915.
=> SyntaxSetBuilder: De-duplicate `link_ref()` with `find_id()` helper

src/html.rs
=> Fix `font-style: underline;` should be `text-decoration: underline;`

src/highlighting/theme_set.rs
Took me a while to figure out what `god` meant in this context 😅
=> Correct typo

Cargo.toml
=> Bump fancy-regex to 0.11

Cargo.toml, tests/public-api.txt
This version has fixed the bug that caused https://github.com/trishume/syntect/pull/500 CI to invalidly fail.
=> tests: Upgrade to public-api 0.33.0

Cargo.toml, tests/public-api.txt
Which has a bugfix for a bugfix
(https://github.com/Enselic/cargo-public-api/pull/518).
=> tests: Upgrade to public-api 0.33.1

.github/workflows/CI.yml
To get rid of warnings about us using Node 16.
=> workflows: actions/checkout@v3 -> v4

Readme.md
Syntect is an awesome code highlight library,  it helps me craft CodeSnap.nvim, thx for the Syntect team!
=> feat(doc): add CodeSnap.nvim to "Projects using Syntect" chapter

Readme.md
A small CLI that allows for generating a syntax-highlighted PDF of code (or any directory with text files).
It also works with images (embeds them into the document on their own page)
Repo is https://github.com/Tommypop2/code-to-pdf
=> Add `code-to-pdf`

Readme.md
Hi! Thought I'd add [Comrak](https://github.com/kivikakk/comrak) to the list. :)
Not knowing how long other projects have been using syntect, I don't really know where to put it in the list (Comrak added syntect integration in 2021), so I'm adding it at the bottom.
=> Readme: list Comrak.
